<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Accounts</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <a href="<?= $this->url('accounts', array('action' => 'index')); ?>"><li class="breadcrumb-item">Accounts Details</li></a>
                         <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Add</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>


<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Add Accounts Details</h3>
            <div class="block-options">
                <button type="button" class="btn-block-option" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
            </div>
        </div>
        <div class="block-content">
            <div class="col-md-12 table-responsive" id="hide">
                <form name="accountsInformation" id="accountsInformation"  class="mb-5" action="<?= $this->url('accounts', array('action' => 'add')); ?>" method="post">
                    <div class="js-wizard-simple block block block-rounded block-bordered">
                        <ul class="nav nav-tabs nav-tabs-block nav-justified" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" href="javascript:void(0);" id="step1" onclick="validateStep4()">Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="javascript:void(0);" id="step2" onclick="validateStep1();">Registratiin & Del.Address</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="javascript:void(0);" id="step3" onclick="validateStep2();">General</a>
                            </li>
                        </ul>  
                        <div class="block-content block-content-full tab-content" style="min-height: 300px;">
                            <div class="tab-pane active" id="wizard-progress-step1" role="tabpanel"> 
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="account_type">Select Account Type</label>
                                    <div class="col-sm-4">
                                        <select class="form-control " id="account_type" name="account_type" placeholder="Enter the account type" title="Please enter the account type">
                                            <option value="">--select--</option>
                                            <?php foreach($accountType as $type){?>
                                                <option value="<?php echo $type->account_type_id;?>"><?php echo $type->account_type_name;?></option>
                                            <?php }?>
                                        </select>
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="account_name_tamil">Account Name</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control " id="account_name_tamil" name="account_name_tamil" placeholder="Enter the account name" title="Please enter the account name">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="account_email">Email</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control " id="account_email" name="account_email" placeholder="Enter the account email" title="Please enter the account email">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="account_city">City</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control " id="account_city" name="account_city" placeholder="Enter the account city" title="Please enter the account city">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="account_pincode">Pincode</label>
                                    <div class="col-sm-4">
                                        <input type="number" class="form-control " id="account_pincode" name="account_pincode" placeholder="Enter the account pincode" title="Please enter the account pincode">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="account_mobile">Mobile</label>
                                    <div class="col-sm-4">
                                        <input type="number" class="form-control " id="account_mobile" name="account_mobile" placeholder="Enter the account mobile" title="Please enter the account mobile">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="account_area">Area</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control " id="account_area" name="account_area" placeholder="Enter the account area" title="Please enter the account area">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="account_status">Status</label>
                                    <div class="col-sm-4">
                                        <select class="form-control " id="account_status" name="account_status" title="Please select the account status">
                                            <option value="active">Active</option>
                                            <option value="inactive">Inactive</option>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="account_address">Address</label>
                                    <div class="col-sm-4">
                                        <textarea type="text" class="form-control " id="account_address" name="account_address" placeholder="Enter the account area" title="Please enter the account area"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="wizard-progress-step2" role="tabpanel">
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_register_tin">TIN No</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control register " id="accounts_register_tin" name="accounts_register_tin" placeholder="Enter the TIN No" title="Please enter the TIN No">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_register_cst">CST No</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control register " id="accounts_register_cst" name="accounts_register_cst" placeholder="Enter the CST No" title="Please enter the CST No">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_register_licence">Licence No</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control register " id="accounts_register_licence" name="accounts_register_licence" placeholder="Enter the licence no" title="Please enter the licence no">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_register_code">Area Code</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control register " id="accounts_register_code" name="accounts_register_code" placeholder="Enter the area code" title="Please enter the area code">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_register_gstin">GSTIN/UIN</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control register " id="accounts_register_gstin" name="accounts_register_gstin" placeholder="Enter the GSTIN/UIN" title="Please enter the GSTIN/UIN">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_register_delivery_name">Delivery Name</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control register " id="accounts_register_delivery_name" name="accounts_register_delivery_name" placeholder="Enter the delivery name" title="Please enter the delivery name">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_register_address">Address</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control register " id="accounts_register_address" name="accounts_register_address" placeholder="Enter the address" title="Please enter the address">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_register_area">Area</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control register " id="accounts_register_area" name="accounts_register_area" placeholder="Enter the area" title="Please enter the area">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_register_city">City</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control register " id="accounts_register_city" name="accounts_register_city" placeholder="Enter the city" title="Please enter the city">
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="wizard-progress-step3" role="tabpanel">
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_general_connection_date">Connection Date</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="js-datepicker form-control" id="accounts_general_connection_date" name="accounts_general_connection_date" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" value="" placeholder="Enter the connection date" title="Please enter the connection date" readonly="readonly">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_general_connection_type">Connection Type</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_connection_type" name="accounts_general_connection_type" placeholder="Enter the connection type" title="Please enter the connection type">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_general_deposite_amount">Deposite Amount</label>
                                    <div class="col-sm-4">
                                        <input type="number" class="form-control general " id="accounts_general_deposite_amount" name="accounts_general_deposite_amount" placeholder="Enter the connection date" title="Please enter the connection date">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_general_rent_amount">Rent Amount</label>
                                    <div class="col-sm-4">
                                        <input type="number" class="form-control general " id="accounts_general_rent_amount" name="accounts_general_rent_amount" placeholder="Enter the connection type" title="Please enter the connection type">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_general_category">Category</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_category" name="accounts_general_category" placeholder="Enter the category" title="Please enter the category">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_general_work_period">Work Period upto</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_work_period" name="accounts_general_work_period" placeholder="Enter the work period upto" title="Please enter the work period upto">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_general_reference">Reference</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_reference" name="accounts_general_reference" placeholder="Enter the reference" title="Please enter the reference">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_general_sender_id">Sender Id</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_sender_id" name="accounts_general_sender_id" placeholder="Enter the sender id" title="Please enter the sender id">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_general_brand">Brand</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_brand" name="accounts_general_brand" placeholder="Enter the brand" title="Please enter the brand">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_general_purchase_disc">Purchase Disc Rate</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_purchase_disc" name="accounts_general_purchase_disc" placeholder="Enter the puchase disc rate" title="Please enter the puchase disc rate">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_general_sales_disc">Sales Disc Rate</label>
                                    <div class="col-sm-4">
                                        <input type="number" class="form-control general " id="accounts_general_sales_disc" name="accounts_general_sales_disc" placeholder="Enter the sales disc rate" title="Please enter the sales disc rate">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_general_wage">Wage/ Cooly/ Fees</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_wage" name="accounts_general_wage" placeholder="Enter the wage/ cooly/ fees" title="Please enter the wage/ cooly/ fees">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_general_price_list">Price List</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_price_list" name="accounts_general_price_list" placeholder="Enter the price list" title="Please enter the price list">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_general_overtime">Overtime Wage/ Cooly</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_overtime" name="accounts_general_overtime" placeholder="Enter the overtime wage/ cooly" title="Please enter the overtime wage/ cooly">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_general_receipt_charges">Receipt and Charges Grp</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_receipt_charges" name="accounts_general_receipt_charges" placeholder="Enter the receipt charges" title="Please enter the receipt charges">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_general_salesman">Salesman</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_salesman" name="accounts_general_salesman" placeholder="Enter the salesman" title="Please enter the salesman">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="accounts_general_salesman_mobile">Salesman Mobile</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_salesman_mobile" name="accounts_general_salesman_mobile" placeholder="Enter the salesman mobile" title="Please enter the salesman mobile">
                                    </div>
                                    
                                    <label class="col-sm-2 col-form-label" for="accounts_general_contact_person">Contact Person</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control general " id="accounts_general_contact_person" name="accounts_general_contact_person" placeholder="Enter the contact person" title="Please enter the contact person">
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <div class="custom-control custom-switch mb-1 pl-4 col-sm-6">
                                        <input type="checkbox" class="custom-control-input" id="accounts_general_permanent" name="accounts_general_permanent" title="Please select options">
                                        <label class="custom-control-label" for="accounts_general_permanent">Cable Permanent Disconnection</label>
                                    </div>
                                    <div class="custom-control custom-switch mb-1 pl-4 col-sm-6">
                                        <input type="checkbox" class="custom-control-input" id="accounts_general_warning_outstanding" name="accounts_general_warning_outstanding" title="Please select options">
                                        <label class="custom-control-label" for="accounts_general_warning_outstanding">Show Warning for Outstanding above</label>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="custom-control custom-switch mb-1 pl-4 col-sm-6">
                                        <input type="checkbox" class="custom-control-input" id="accounts_general_invoice_outstanding" name="accounts_general_invoice_outstanding" title="Please select options">
                                        <label class="custom-control-label" for="accounts_general_invoice_outstanding">Looks Sales Invoice when outstanding abobe</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="button" class="btn btn-secondary nxtBtn" onclick="validateStep1()" style="float: right;margin-bottom: 15px; ">Registratiin & Del.Address<i class="fa fa-angle-right ml-1"></i></button>
                    <button type="button" class="btn btn-secondary nxtBtn2" onclick="validateStep2()" style="display:none; float: right;margin-bottom: 15px; ">General<i class="fa fa-angle-right ml-1"></i></button>
                    <button type="button" class="btn btn-secondary btnHide2" onclick="validateStep3()" style="display:none;"><i class="fa fa-angle-left mr-1"></i>Registratiin & Del.Address</button>
                    <button type="button" class="btn btn-secondary btnHide" onclick="validateStep4()" style="display:none;"><i class="fa fa-angle-left mr-1"></i>Name</button>
                    <div class="row items-push submit" style="display:none;">
                        <div class="col-lg-7 offset-lg-4">
                            <a href="<?= $this->url('accounts', array('action' => 'index')); ?>" class="btn btn-danger">Cancel</a>&nbsp;
                            <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'accountsInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('accountsInformation').submit();
            }
        }
    }

    function validateStep1()
    {
        flag = deforayValidator.init({
            formId: 'accountsInformation'
        });
        $("#step1,#wizard-progress-step1,#step3,#wizard-progress-step3").removeClass("active");
        $("#step2,#wizard-progress-step2").addClass("active");
        $(".nxtBtn,.btnHide2,.submit").hide();
        $(".btnHide,.nxtBtn2").show();
    }

    function validateStep2()
    {
        flag = deforayValidator.init({
            formId: 'accountsInformation'
        });
        $("#step1,#wizard-progress-step1,#step2,#wizard-progress-step2").removeClass("active");
        $("#step3,#wizard-progress-step3").addClass("active");

        $(".nxtBtn,.nxtBtn2,.btnHide").hide();
        $(".btnHide2,.submit").show();
    }
    
    function validateStep3()
    {
        flag = deforayValidator.init({
            formId: 'accountsInformation'
        });
        $("#step1,#wizard-progress-step1,#step3,#wizard-progress-step3").removeClass("active");
        $("#step2,#wizard-progress-step2").addClass("active");
        $(".nxtBtn2,.btnHide,.submit").show();
        $(".nxtBtn,.btnHide2").hide();
    }
    
    function validateStep4()
    {
        flag = deforayValidator.init({
            formId: 'accountsInformation'
        });
        $("#step1,#wizard-progress-step1").addClass("active");
        $("#step2,#wizard-progress-step2,#step3,#wizard-progress-step3").removeClass("active");

        $(".nxtBtn2,.btnHide,.btnHide2,.submit").hide();
        $(".nxtBtn").show();
        
    }
</script>
