<?php
use Zend\Session\Container;
use Zend\Validator\InArray;
$sessionLogin = new Container('user');
// \Zend\Debug\Debug::dump($accounts);die;
?>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Accounts</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <a href="<?= $this->url('accounts', array('action' => 'index')); ?>"><li class="breadcrumb-item">Accounts Details</li></a>
                         <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Edit</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>


<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Edit Accounts Details</h3>
        </div>
        <div class="block-content">
            <div class="col-md-12 table-responsive" id="hide">
                <form name="accountsInformation" id="accountsInformation"  class="mb-5" action="<?= $this->url('accounts', array('action' => 'edit')); ?>" method="post">
                    
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="type">Select Account Type<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="type" name="type" placeholder="Enter the account type" title="Please enter the account type">
                                <option value="">--select--</option>
                                <option value="balance-sheet" <?php echo($accounts->account_type == 'balance-sheet' )?'selected="selected"':'';?>>Balance Sheet</option>
                                <option value="profit-and-loss" <?php echo($accounts->account_type == 'profit-and-loss' )?'selected="selected"':'';?>>Profit and Loss</option>
                            </select>
                        </div>
                        
                        <label class="col-sm-2 col-form-label" for="name">Account Name<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $accounts->account_name_tamil;?>" class="form-control isRequired" id="name" name="name" placeholder="Enter the account name" title="Please enter the account name">
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="email">Email<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $accounts->account_email;?>" class="form-control isRequired" id="email" name="email" placeholder="Enter the account email" title="Please enter the account email">
                        </div>
                        
                        <label class="col-sm-2 col-form-label" for="city">City<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $accounts->account_city;?>" class="form-control isRequired" id="city" name="city" placeholder="Enter the city" title="Please enter the city">
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="pincode">Pincode<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="number" value="<?php echo $accounts->account_pincode;?>" class="form-control isRequired" id="pincode" name="pincode" placeholder="Enter the pincode" title="Please enter the pincode">
                        </div>
                        
                        <label class="col-sm-2 col-form-label" for="mobile">Mobile<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="number" value="<?php echo $accounts->account_mobile;?>" class="form-control isRequired" id="mobile" name="mobile" placeholder="Enter the mobile" title="Please enter the mobile">
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="artist">Area<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $accounts->account_area;?>" class="form-control isRequired" id="area" name="area" placeholder="Enter the area" title="Please enter the area">
                        </div>
                        
                        <label class="col-sm-2 col-form-label" for="accountStatus">Status<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="accountStatus" name="accountStatus" title="Please select the account status">
                                <option value="">--select--</option>
                                <option value="active" <?php echo($accounts->account_status == 'active' )?'selected="selected"':'';?>>Active</option>
                                <option value="inactive" <?php echo($accounts->account_status == 'inactive' )?'selected="selected"':'';?>>Inactive</option>
                            </select>
                        </div>
                    </div>
                        
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="address">Address<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <textarea type="text" value="<?php echo $accounts->account_address;?>" class="form-control isRequired" id="address" name="address" placeholder="Enter the address" title="Please enter the address"></textarea>
                        </div>
                    </div>
                    
                    <div class="row items-push">
                        <input type="hidden" value="<?php echo $accounts->account_id;?>" name="accountId">
                        <div class="col-lg-7 offset-lg-4">
                            <a href="<?= $this->url('accounts', array('action' => 'index')); ?>" class="btn btn-danger">Cancel</a>&nbsp;
                            <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'accountsInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('accountsInformation').submit();
            }
        }
    }
</script>
