<?php
    use Zend\Session\Container;
    $editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center",bSortable:false}';
?>
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Accounts Details</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="<?php echo $this->url('accounts',array('action' => 'add'));?>" class="btn btn-primary pull-right" style="margin-top:-5px;"><i class="fa fa-plus"></i>&nbsp;Add New Account</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            
        </div>
        <div class="block-content block-content-full">
            <table id="accountsDataTable" class="table table-bordered table-striped table-vcenter">
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Name</th>
                        <th>City</th>
                        <th>Area</th>
                        <th>Mobile</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="7" class="dataTables_empty">Loading data from server</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    /* Table initialisation */
   oTable = null;
    $(document).ready(function() {
        oTable = $('#accountsDataTable').dataTable( {
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [
                    <?= $editAction;?>
            ],
            "sAjaxSource": "<?= $this->url('accounts',array('action' => 'index')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        } );
    } );

    function deleteAccount(id){
        conf=confirm("Are you sure, you want delete this account!");
		if(conf){
			$.post("<?php echo $this->url('accounts',array('action'=>'delete')); ?>",{account_id:id},
			function(data){
				if(data>0){
					oTable.fnDraw();
					alert("Account deleted successfully.");
				}else{
					alert("Account not deleted!",'err');
                }
			});
		}
    }
</script>