<?= $this->doctype()
// use Zend\Session\Container;
// $container = new Container('alert');
// $loginContainer = new Container('user');
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>Jewellery Shop</title>
        <meta name="description" content="Jewellery Shop Management">
        <!-- Icons -->
        <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
        <link rel="shortcut icon" href="assets/media/favicons/favicon.png">
        <link rel="icon" type="image/png" sizes="192x192" href="assets/media/favicons/favicon-192x192.png">
        <link rel="apple-touch-icon" sizes="180x180" href="assets/media/favicons/apple-touch-icon-180x180.png">
        <!-- END Icons -->

        <!-- Stylesheets -->
        <!-- Fonts and Dashmix framework -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,400i,600,700">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="<?= $this->basePath('/assets/css/dashmix.min.css')?>" rel="stylesheet">
        <!-- END Stylesheets -->
    </head>
    <body>
        <!-- Page Container -->
        <div id="page-container">

            <!-- Main Container -->
            <main id="main-container">

                <!-- Page Content -->

                <!-- <div class="bg-video" data-vide-bg="< ?= $this->basePath('/assets/media/videos/city_night')?>" data-vide-options="posterType: jpg"> -->

                <div class="bg-image" style="background-image: url(<?= $this->basePath('/assets/media/photos/office.jpg')?>);">
                    <div class="row no-gutters bg-primary-op">
                        <!-- Main Section -->
                        <div class="hero-static col-md-6 d-flex align-items-center bg-white">
                            <div class="p-3 w-100">
                                <!-- Header -->
                                <div class="mb-3 text-center">
                                    <a class="link-fx font-w700 font-size-h1" href="/">
                                        <span class="text-dark">Jewellery</span> <span class="text-primary">Shop</span>
                                    </a>
                                    <p class="text-uppercase font-w700 font-size-sm text-muted">Jewellery Shop Management</p>

                                </div>
                                <!-- END Header -->

                                <div class="row no-gutters justify-content-center">
                                    <div class="col-sm-8 col-xl-6">
                                        <form class="js-validation-signin" name="adminLoginInformation" action="<?= $this->url('login',array('action'=>'index')); ?>" method="post" autocomplete="off" onsubmit="return doLogin();return false;">
                                            <div class="py-3">
                                                <div class="form-group">
                                                    <input type="text" class="form-control form-control-lg form-control-alt" id="userName" name="userName" placeholder="Email">
                                                </div>
                                                <div class="form-group">
                                                    <input type="password" class="form-control form-control-lg form-control-alt" id="password" name="password" placeholder="Password">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-block btn-hero-lg btn-hero-primary" onClick="doLogin();return false;" >
                                                    <i class="fa fa-fw fa-sign-in-alt mr-1"></i> Sign In
                                                </button>
                                                
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <!-- END Sign In Form -->
                            </div>
                        </div>
                        <!-- END Main Section -->

                        <!-- Meta Info Section -->
                        <div class="hero-static col-md-6 d-none d-md-flex align-items-md-center justify-content-md-center text-md-center">
                            <div class="p-3">
                                <p class="display-4 font-w700 text-white mb-3">
                                    Welcome to the Future
                                </p>
                                <p class="font-size-lg font-w600 text-white-75 mb-0">
                                    &copy; <span class="js-year-copy"><?= date('Y'); ?></span>
                                </p>
                            </div>
                        </div>
                        <!-- END Meta Info Section -->
                    </div>
                </div>
                <!-- END Page Content -->
            </main>
            <!-- END Main Container -->
        </div>
        <!-- END Page Container -->

        <script src="<?= $this->basePath('/assets/js/dashmix.core.min.js') ?>"></script>
        <script src="<?= $this->basePath('/assets/js/plugins/jquery-validation/jquery.validate.min.js') ?>"></script>
        <script src="<?= $this->basePath('/assets/js/plugins/vide/jquery.vide.min.js') ?>"></script>
        <script src="<?= $this->basePath('/assets/js/pages/deforayValidation.js') ?>"></script>
        <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>

        <script type="text/javascript">
            duplicateName = true;
            $(document).ready(function() {
                <?php
                if (isset($container->alertMsg) && $container->alertMsg != "") {
                ?>
                alert("<?= $container->alertMsg; ?>");
                <?=
                $container->alertMsg = "";
                unset($container->alertMsg);
                }
                ?>
            });
            function doLogin(){
                duplicateName = true;
                flag = deforayValidator.init({
                    formId: 'adminLoginInformation'
                });

                if(flag){
                    document.getElementById('adminLoginInformation').submit();
                }
            }


        </script>
    </body>
</html>
