<?php 
use Zend\Session\Container;
$alertContainer = new Container('alert');
$sessionLogin = new Container('user');
$role = $sessionLogin->roleId;
$roleCode = $sessionLogin->roleCode;
$userName = $sessionLogin->userName;
$name = $sessionLogin->name;

$masterMenu = "";
$masterMenu.="<li id='nav-main-item'><a id='user' class='nav-main-link' href=". $this->url('user', array('action' => 'index')) ."><span class='nav-main-link-name'>Admin User Details</span></a></li>";
$masterMenu.="<li id='nav-main-item'><a id='accounts' class='nav-main-link' href=". $this->url('accounts', array('action' => 'index')) ."><span class='nav-main-link-name'>Accounts Details</span></a></li>";
$masterMenu.="<li id='nav-main-item'><a id='products' class='nav-main-link' href=". $this->url('products', array('action' => 'index')) ."><span class='nav-main-link-name'>Manage Products</span></a></li>";
$masterMenu.="<li id='nav-main-item'><a id='vat' class='nav-main-link' href=". $this->url('vat', array('action' => 'index')) ."><span class='nav-main-link-name'>Manage GST</span></a></li>";
// $masterMenu.="<li id='nav-main-item'><a id='gold-chit' class='nav-main-link' href=". $this->url('gold-chit', array('action' => 'index')) ."><span class='nav-main-link-name'>Manage GoldChit</span></a></li>";

$entryMenu = "";
$entryMenu.="<li id='nav-main-item'><a id='sales' class='nav-main-link' href=". $this->url('sales', array('action' => 'index')) ."><span class='nav-main-link-name'>Manage Sales</span></a></li>";

$reportsMenu = "";
$reportsMenu.="<li id='nav-main-item'><a id='reports-sales' class='nav-main-link' href=". $this->url('reports-sales', array('action' => 'index')) ."><span class='nav-main-link-name'>Sales Report</span></a></li>";
$reportsMenu.="<li id='nav-main-item'><a id='reports-products' class='nav-main-link' href=". $this->url('reports-products', array('action' => 'index')) ."><span class='nav-main-link-name'>Products Report</span></a></li>";
?>
<?= $this->doctype() ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">


    <title>Jewellery Shop</title>

    <link rel="shortcut icon" href="<?= $this->basePath().'/assets/media/favicons/favicon.png';?>">


    <link rel="icon" type="image/png" sizes="192x192" href="<?= $this->basePath().'/assets/media/favicons/favicon-192x192.png';?>">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= $this->basePath().'/assets/media/favicons/apple-touch-icon-180x180.png';?>">

    <style>
      .mandatory{
        color:red;
      }
      .not-mandatory{
        color:#FFFFFF;
      }
      input[type=number]::-webkit-inner-spin-button, 
      input[type=number]::-webkit-outer-spin-button { 
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        margin: 0; 
      }
      .form-control[readonly] {
        background-color: transparent;
        opacity: 1;
      }
    </style>
    <!-- Stylesheets -->
    <!-- Fonts and Dashmix framework -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,400i,600,700">

    <link rel="stylesheet" href="<?= $this->basePath() . '/assets/css/dashmix.min.css'?>" rel="stylesheet">
    <link rel="stylesheet" href="<?= $this->basePath() . '/assets/css/alert.css'?>" rel="stylesheet">
    <link rel="stylesheet" href="<?= $this->basePath() . '/assets/js/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css'?>" rel="stylesheet">
    <script src="<?= $this->basePath() . '/js/jquery3.min.js'?>"></script>

    <link rel="stylesheet" href="<?= $this->basePath() . '/assets/css/select2-new.min.css' ?>">
    <link rel="stylesheet" href="<?= $this->basePath() . '/assets/js/plugins/datatables/dataTables.bootstrap4.css'?>" rel="stylesheet">
    <link rel="stylesheet" href="<?= $this->basePath() . '/assets/js/plugins/datatables/buttons-bs4/buttons.bootstrap4.min.css'?>" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/daterangepicker/daterangepicker.css' ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/deforayModal.css' ?>">
  </head>
  <body>
    <!-- Page Container -->
    <div id="page-container" class="sidebar-o enable-page-overlay side-scroll page-header-fixed page-header-dark main-content-narrow">
      <!-- Side Overlay-->
      <aside id="side-overlay">
        <!-- Side Header -->
        <div class="bg-image" style="background-image: url('<?= $this->basePath().'/assets/media/various/bg_side_overlay_header.jpg';?>');">
          <div class="bg-primary-op">
            <div class="content-header">
              <!-- User Avatar -->
              <a class="img-link mr-1" href="be_pages_generic_profile.html">
              <img class="img-avatar img-avatar48" src="<?= $this->basePath().'/assets/media/avatars/avatar10.jpg';?>" alt="">
              </a>
              <!-- END User Avatar -->

              <!-- User Info -->
              <div class="ml-2">
                <a class="text-white font-w600" href="#"></a>
                <div class="text-white-75 font-size-sm font-italic"></div>
              </div>
              <!-- END User Info -->

              <!-- Close Side Overlay -->
              <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
              <a class="ml-auto text-white" href="javascript:void(0)" data-toggle="layout" data-action="side_overlay_close">
                <i class="fa fa-times-circle"></i>
              </a>
              <!-- END Close Side Overlay -->
            </div>
          </div>
        </div>
        <!-- END Side Header -->
      </aside>
      <!-- END Side Overlay -->

      <nav id="sidebar" aria-label="Main Navigation">
        <!-- Side Header -->
        <div class="bg-header-dark">
          <div class="content-header bg-white-10">
            <!-- Logo -->
            <a class="link-fx font-w600 font-size-lg text-white" href="/">
                <span class="smini-visible">
                    <span class="text-white">J</span><span class="text-white">S</span>
                </span>
                <span class="smini-hidden">
                    <span class="text-white">Jewellery</span><span class="text-white">Shop</span>
                </span>
            </a>
            <!-- <a class="link-fx font-w600 font-size-md text-white" href="/" style=" font-size: 20px; ">
              <span class="text-white">Jewellery</span>&nbsp;<span class="text-white-75">Shop</span>
            </a> -->
            <div>
                <!-- <a class="js-class-toggle text-white-75 js-class-toggle-enabled" data-class="fa-toggle-off fa-toggle-on" data-toggle="layout" data-action="sidebar_mini_toggle" href="javascript:void(0)"><i class="fa fa-toggle-off" id="sidebar-style-toggler"></i></a>
                <a class="js-class-toggle text-white-75 js-class-toggle-enabled" data-target="#sidebar-style-toggler" data-class="fa-toggle-off fa-toggle-on" data-toggle="layout" data-action="sidebar_style_toggle" href="javascript:void(0)">
                    <i class="fa fa-toggle-off" id="sidebar-style-toggler"></i>
                </a>
                <a class="d-lg-none text-white ml-2" data-toggle="layout" data-action="sidebar_close" href="javascript:void(0)">
                    <i class="fa fa-times-circle"></i>
                </a> -->
            </div>
            <!-- END Logo -->
          </div>
        </div>
        <!-- END Side Header -->

        <!-- Side Navigation -->
        <div class="content-side content-side-full">
          <ul class="nav-main">
            <li class="nav-main-item">
            <!--  -->
              <a class="nav-main-link" href="/">
                <i class="nav-main-link-icon si si-cursor"></i>
                <span class="nav-main-link-name">Dashboard</span>
                <!-- <span class="nav-main-link-badge badge badge-pill badge-success">5</span> -->
              </a>
            </li>
            <li class="nav-main-heading"></li>
            <li class="nav-main-item " id="master">
              <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="true" href="#">
                <i class="nav-main-link-icon si si-wrench"></i>
                <span class="nav-main-link-name ">Master</span>
              </a>
              <ul class="nav-main-submenu">
                  <?= $masterMenu;?>
              </ul>
            </li>
            <li class="nav-main-item" id="entry">
              <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="true" href="#">
                <i class="nav-main-link-icon far fa-edit"></i>
                <span class="nav-main-link-name ">Entry</span>
              </a>
              <ul class="nav-main-submenu">
                  <?= $entryMenu;?>
              </ul>
            </li>
            <li class="nav-main-item" id="reports">
              <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="true" href="#">
                <i class="nav-main-link-icon si si-notebook"></i>
                <span class="nav-main-link-name ">Reports</span>
              </a>
              <ul class="nav-main-submenu">
                  <?= $reportsMenu;?>
              </ul>
            </li>
          </ul>
        </div>
        <!-- END Side Navigation -->
      </nav>
      <!-- END Sidebar -->

      <header id="page-header">
        <!-- Header Content -->
        <div class="content-header">
          <!-- Left Section -->
          <div>
            <!-- Toggle Sidebar -->
            <button type="button" class="btn btn-dual mr-1" data-toggle="layout" data-action="sidebar_toggle">
              <i class="fa fa-fw fa-bars"></i>
            </button>
            <!-- END Toggle Sidebar -->
          </div>
          <!-- END Left Section -->

          <!-- Right Section -->
          <div>
            <button type="button" class="btn btn-dual" data-toggle="modal" data-target="#modal-block-popin" data-action="side_overlay_toggle">
                <i class="far fa-fw fa-list-alt"></i>
                <span>Today Price&nbsp;&nbsp;&nbsp;</span>
                <span>Gold: ₹<span id="gold">3000</span>&nbsp;&nbsp;</span>
                <span>Silver: ₹<span id="silver">40</span></span>
            </button>

            <!-- User Dropdown -->
            <div class="dropdown d-inline-block">
              <button type="button" class="btn btn-dual" id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-user d-sm-none"></i>
              <span class="d-none d-sm-inline-block"><?= $name; ?></span>
              <i class="fa fa-fw fa-angle-down ml-1 d-none d-sm-inline-block"></i>
              </button>
              <div class="dropdown-menu dropdown-menu-right p-0" aria-labelledby="page-header-user-dropdown">
                <div class="p-2">
                  <a class="dropdown-item"  href="/user/edit-profile/<?= base64_encode($sessionLogin->userId);?>">
                      <i class="far fa-fw fa-user mr-1"></i> Edit Profile
                  </a>
                  <div role="separator" class="dropdown-divider"></div>
                  <a class="dropdown-item"  href="/logout">
                      <i class="far fa-fw fa-arrow-alt-circle-left mr-1"></i> Sign Out
                  </a>
                  
                </div>
              </div>
            </div>
            
            <!-- END User Dropdown -->
          </div>
          <!-- END Right Section -->
        </div>
        <!-- END Header Content -->
        <!-- Header Loader -->
        <!-- Please check out the Loaders page under Components category to see examples of showing/hiding it -->
        <div id="page-header-loader" class="overlay-header bg-primary-darker">
          <div class="content-header">
            <div class="w-100 text-center">
              <i class="fa fa-fw fa-2x fa-sun fa-spin text-white"></i>
            </div>
          </div>
        </div>
        <!-- END Header Loader -->
      </header>
      <!-- END Header -->
      <!-- END Header -->
      <main id="main-container">
      <!-- Hero -->
        <?= $this->content; ?>
      <!-- END Hero -->
      </main>
      <!-- END Main Container -->
      <!-- Footer -->
      <div id="dDiv" class="dialog"> 
          <div style="text-align:center"><span onclick="closeModal();" style="float:right;clear:both;" class="closeModal"></span></div> 
          <iframe id="dFrame" src="" style="border:none;" scrolling='yes' marginwidth='0' marginheight='0' frameborder='0' vspace='0' hspace='0' >some problem</iframe> 
      </div>
      <footer id="page-footer" class="bg-body-light">
        <div class="content py-0">
          <div class="row font-size-sm">
            <div class="col-sm-6 order-sm-1 text-center text-sm-left">
              <strong>Copyright &copy; <?= date('Y');?> <a href="#"></a></strong> All rights reserved.
            </div>
          </div>
        </div>
      </footer>
      <!-- END Footer -->
    </div>
    <!-- END Page Container -->
    <div style="display:none" class="modal fade show" id="modal-block-popin" tabindex="-1" role="dialog" aria-labelledby="modal-block-popin" style="display: block; padding-right: 15px;">
        <div class="modal-dialog modal-dialog-popin" role="document">
            <div class="modal-content">
                <div class="block block-themed block-transparent mb-0">
                    <div class="block-header bg-primary-dark">
                        <h3 class="block-title">Update Today Price</h3>
                        <div class="block-options">
                            <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                                <i class="fa fa-fw fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="block-content">
                      <form id="priceTable" name="priceTable">
                        <div class="form-group row">
                          <label for="vnooiceNo" class="col-md-2 control-label" for="gold_rate">Gold Rate <span class="mandatory">*</span></label>
                          <div class="col-md-4">
                              <input type="number" class="form-control isRequired" id="gold_rate" name="gold_rate" placeholder="Gold Rate" title="Please enter the gold price"/>
                          </div>

                          <label for="vnooiceDate" class="col-md-2 control-label" for="silver_rate">silver Rate <span class="mandatory">*</span></label>
                          <div class="col-md-4">
                            <input type="number" class="form-control isRequired" id="silver_rate" name="silver_rate" placeholder="Silver Rate" title="Please enter the silver price"/>
                          </div>
                        </div>
                        <input type="hidden" class="form-control" id="price_id" name="price_id"/>
                      </form>
                    </div>
                    <div class="block-content block-content-full text-right bg-light">
                        <button type="button" class="btn btn-sm btn-light" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-sm btn-primary" onclick="savePrice();return false;">Update</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="<?= $this->basePath() . '/js/jquery2.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/alert.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/dashmix.core.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js'; ?>"></script>

    <script src="<?= $this->basePath() . '/assets/js/dashmix.app.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/pages/be_forms_validation.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/plugins/jquery-validation/jquery.validate.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/plugins/jquery-validation/additional-methods.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/pages/deforayValidation.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/jquery.blockUI.js'; ?>"></script>

    <script src="<?= $this->basePath() . '/assets/js/plugins/datatables/jquery.dataTables.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/plugins/datatables/dataTables.bootstrap4.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/plugins/datatables/buttons/dataTables.buttons.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/plugins/datatables/buttons/buttons.print.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/plugins/datatables/buttons/buttons.html5.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/plugins/datatables/buttons/buttons.flash.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/plugins/datatables/buttons/buttons.colVis.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/pages/be_tables_datatables.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/select2.full.min.js'; ?>"></script>
    <script>jQuery(function(){ Dashmix.helpers(['datepicker', 'colorpicker', 'maxlength', 'select2', 'rangeslider']); });</script>
    <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>

    <script src="<?= $this->basePath() . '/assets/js/plugins/jquery-bootstrap-wizard/bs4/jquery.bootstrap.wizard.min.js'; ?>"></script>
    <script src="<?= $this->basePath() . '/assets/js/pages/be_forms_wizard.min.js'; ?>"></script>
    <script src="<?php echo $this->basePath() . '/assets/js/deforayModal.js'; ?>"></script>

    <script type="text/javascript">
    function savePrice(){
        flag = deforayValidator.init({
            formId: 'priceTable'
        });
        if(flag){
            $.blockUI();
            var gold_rate = $('#gold_rate').val();
            var silver_rate = $('#silver_rate').val();
            var price_id = $('#price_id').val();
            $.post("<?php echo $this->url('sales',array('action'=>'price-update')); ?>",{gold_rate:gold_rate,silver_rate:silver_rate,price_id:price_id},
            function(data){
              if(data>0){
                alert("Sales updated successfully.");
                location.reload(true);
                $.unblockUI();
              }else{
                alert("Sales not updated!",'err');
                $.unblockUI();
              }
            });
        }
    }
    function viewPrice(){
      $.post("<?php echo $this->url('sales',array('action'=>'price')); ?>",
      function(data){
        var result=data.split('-');
        document.getElementById("gold").textContent=result[0];
        document.getElementById("silver").textContent=result[1];
        document.getElementById("price_id").value=result[2];
        document.getElementById("gold_rate").value=result[0];
        document.getElementById("silver_rate").value=result[1];
      });
    }

    function showModal(url, w, h) {
        showdefModal('dDiv', w, h);
        document.getElementById('dFrame').style.height = h + 'px';
        document.getElementById('dFrame').style.width = w + 'px';
        document.getElementById('dFrame').src = url;
    }

    function closeModal() {
        document.getElementById('dFrame').src = "";
        hidedefModal('dDiv');
    }

    $(document).ready(function() {
      <?php if(isset($alertContainer->alertMsg) && $alertContainer->alertMsg != "") { ?>
          alert("<?php echo $alertContainer->alertMsg; ?>"); 
          <?php $alertContainer->alertMsg = "";
          unset($alertContainer->alertMsg);
      }?>
      viewPrice();
    });
    $(function () {
      str=$(location).attr('pathname');
      splitsUrl=str.split("/",4);
      if( splitsUrl[1]=='accounts' || splitsUrl[1]=='user' || splitsUrl[1]=='products' || splitsUrl[1]=='vat' || splitsUrl[1]=='gold-chit')
      {
          $('#master').addClass('open');
          $('#'+splitsUrl[1]).addClass('active');
      }
      if( splitsUrl[1]=='sales')
      {
          $('#entry').addClass('open');
          $('#'+splitsUrl[1]).addClass('active');
      }
      if( splitsUrl[1]=='reports-sales' || splitsUrl[1]=='reports-products')
      {
          $('#reports').addClass('open');
          $('#'+splitsUrl[1]).addClass('active');
      }
    });
    </script>
  </body>
</html>
