<?php
use Zend\Session\Container;
$alertContainer = new Container('alert');
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>GFImpex</title>
		<!-- Tell the browser to be responsive to screen width -->
		<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
		<!-- Fonts and Dashmix framework -->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,400i,600,700">
		
		<!-- Dashmix Css -->
		<link rel="stylesheet" href="<?= $this->basePath() . '/assets/css/dashmix.min.css'?>" rel="stylesheet">
		<link rel="stylesheet" href="<?= $this->basePath() . '/assets/css/alert.css'?>" rel="stylesheet">
		<link rel="stylesheet" href="<?= $this->basePath() . '/assets/js/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css'?>" rel="stylesheet">
		<script src="<?= $this->basePath() . '/js/jquery3.min.js'?>"></script>
		<link rel="stylesheet" href="<?= $this->basePath() . '/assets/css/select2-new.min.css' ?>">
		<link rel="stylesheet" href="<?= $this->basePath() . '/assets/js/plugins/datatables/dataTables.bootstrap4.css'?>" rel="stylesheet">
		<link rel="stylesheet" href="<?= $this->basePath() . '/assets/js/plugins/datatables/buttons-bs4/buttons.bootstrap4.min.css'?>" rel="stylesheet">
		<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/daterangepicker/daterangepicker.css' ?>">
		<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/deforayModal.css' ?>">
		<style>
			.mandatory{
				color:red;
			}
			.not-mandatory{
				color:#FFFFFF;
			}
			input[type=number]::-webkit-inner-spin-button, 
			input[type=number]::-webkit-outer-spin-button { 
				-webkit-appearance: none;
				-moz-appearance: none;
				appearance: none;
				margin: 0; 
			}
			.form-control[readonly] {
				background-color: transparent;
				opacity: 1;
			}
		</style>
	</head>
	<body class="hold-transition skin-blue sidebar-mini">
		<?php echo $this->content; ?>
		<?php echo (isset($this->aclError) ? $this->aclError : ""); ?>
		<div id="dDiv" class="dialog"> 
			<div style="text-align:center"><span onclick="closeModal();" style="float:right;clear:both;" class="closeModal"></span></div> 
			<iframe id="dFrame" src="" style="border:none;" scrolling='yes' marginwidth='0' marginheight='0' frameborder='0' vspace='0' hspace='0' >some problem</iframe> 
		</div>  
		<!-- Dashmix Js -->
		<script src="<?= $this->basePath() . '/js/jquery2.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/alert.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/dashmix.core.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js'; ?>"></script>

		<script src="<?= $this->basePath() . '/assets/js/dashmix.app.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/pages/be_forms_validation.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/plugins/jquery-validation/jquery.validate.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/plugins/jquery-validation/additional-methods.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/pages/deforayValidation.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/jquery.blockUI.js'; ?>"></script>

		<script src="<?= $this->basePath() . '/assets/js/plugins/datatables/jquery.dataTables.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/plugins/datatables/dataTables.bootstrap4.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/plugins/datatables/buttons/dataTables.buttons.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/plugins/datatables/buttons/buttons.print.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/plugins/datatables/buttons/buttons.html5.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/plugins/datatables/buttons/buttons.flash.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/plugins/datatables/buttons/buttons.colVis.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/pages/be_tables_datatables.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/select2.full.min.js'; ?>"></script>
		<script>jQuery(function(){ Dashmix.helpers(['datepicker', 'colorpicker', 'maxlength', 'select2', 'rangeslider']); });</script>
		<script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>

		<script src="<?= $this->basePath() . '/assets/js/plugins/jquery-bootstrap-wizard/bs4/jquery.bootstrap.wizard.min.js'; ?>"></script>
		<script src="<?= $this->basePath() . '/assets/js/pages/be_forms_wizard.min.js'; ?>"></script>
		<script src="<?php echo $this->basePath() . '/assets/js/deforayModal.js'; ?>"></script>
		<!-- page script -->
		<script> 
			$(function () {
				<?php if(isset($alertContainer->alertMsg) && $alertContainer->alertMsg != "") { ?>
					alert("<?php echo $alertContainer->alertMsg; ?>"); 
					<?php $alertContainer->alertMsg = "";
					unset($alertContainer->alertMsg);
				}?>
			});

			function showModal(url, w, h) {
				showdefModal('dDiv', w, h);
				document.getElementById('dFrame').style.height = h + 'px';
				document.getElementById('dFrame').style.width = w + 'px';
				document.getElementById('dFrame').src = url;
			}
				
			function closeModal() {
				document.getElementById('dFrame').src = "";
				hidedefModal('dDiv');
			}
		</script>
	</body>
</html>
