<?php 
// \Zend\Debug\Debug::dump($sales);die;
$editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
?>
<style>
    .form-control[readonly] {
        background-color: transparent;
        opacity: 1;
    }
</style>
<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Manage Emi Details</h3>
            <div class="block-options">
                <!-- <button type="button" class="btn-block-option" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button> -->
            </div>
        </div>
        <div class="block-content block-content-full">
            <form class="form-horizontal" method='post' name='payForm' id='payForm' autocomplete="off" action="<?= $this->url('sales', array('action' => 'pay')); ?>">
                <div class="box-body">
                    <div class="form-group row">
                        <label for="sales_grand_total" class="col-md-2 control-label">Total Value </label>
                        <div class="col-md-4">
                            <input type="number" value="<?php echo $sales->sales_grand_total; ?>" class="form-control" id="sales_grand_total" name="sales_grand_total" title="Please enter total value" readonly/>
                        </div>
                        
                        <label for="sales_recived" class="col-md-2 control-label">Amount Total Recived </label>
                        <div class="col-md-4">
                            <input type="number"  value="<?php echo $sales->sales_recived; ?>" class="form-control" id="sales_recived" name="sales_recived" title="Please enter recived amount" onchange="updatePay();"/>
                            <input type="hidden"  value="<?php echo $sales->sales_recived; ?>" class="form-control" id="sales_recived_old" name="sales_recived_old" readonly/>
                        </div>
                        
                    </div>
                    
                    <div class="form-group row">
                        <label for="sales_user_id" class="col-md-2 control-label">User <span class="mandatory">*</span></label>
                        <div class="col-md-4">
                            <select class="form-control isRequired" id="sales_user_id" name="sales_user_id" title="Please choose user">
                                <option value="">--select--</option>
                                <?php foreach($usersList as $key=>$user){?>
                                    <option value="<?php echo $user->user_id;?>" <?php echo($sales->sales_user_id == $user->user_id )?'selected="selected"':'';?>><?php echo $user->name;?></option>
                                <?php } ?>
                            </select>
                        </div>
                        
                        <label for="sales_received_type" class="col-md-2 control-label">Received Type <span class="mandatory">*</span></label>
                        <div class="col-md-4">
                            <select class="form-control isRequired" id="sales_received_type" name="sales_received_type" title="Please received type">
                                <option value="">--select--</option>
                                <option value="cash" <?php echo($sales->sales_received_type == 'insurance' )?'selected="selected"':'';?>>Cash</option>
                                <option value="cheque" <?php echo($sales->sales_received_type == 'insurance' )?'selected="selected"':'';?>>Cheque</option>
                                <option value="online" <?php echo($sales->sales_received_type == 'insurance' )?'selected="selected"':'';?>>Online</option>
                                <option value="insurance" <?php echo($sales->sales_received_type == 'insurance' )?'selected="selected"':'';?>>Insurance</option>
                            </select>
                        </div>
                    </div>
                    
                    
                    <div class="form-group row">
                        <label for="sales_balance" class="col-md-2 control-label">Amount Balance </label>
                        <div class="col-md-4">
                            <input type="number"  value="<?php echo $sales->sales_balance; ?>" class="form-control" id="sales_balance" name="sales_balance" title="Please enter balance amount" readonly/>
                        </div>

                        <label for="sales_emi_remarks" class="col-md-2 control-label">Remarks</label>
                        <div class="col-md-4">
                            <textarea type="text" class="form-control" id="sales_emi_remarks" name="sales_emi_remarks" placeholder="Enter the remakrs" title="Please enter remakrs"></textarea>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <input type="hidden" value="<?php echo $sales->sales_id;?>" name="sales_id" id="sales_id"/>
                    <input type="hidden" value="<?php echo isset($sales->sales_emi_id) ? $sales->sales_emi_id : 0;?>" name="sales_emi_id" id="sales_emi_id"/>
                    <input type="button" id="submitBtn" class="btn btn-sm btn-primary" value="Submit" onclick="validateNow();return false;">
                </div>
            </form>
        </div>
    </div>
    
    <div class="block block-rounded block-bordered">
        <div class="block-content block-content-full table-responsive">
            <div class="block-content block-content-full">
                <table id="emiTable" class="display table table-bordered table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th>Voucher No</th>
                            <th>Date</th>
                            <th>Type</th>
                            <th>Emi Amount</th>
                            <th>Remarks</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="5" class="dataTables_empty">Loading data from server</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    oTable = null;
    var receivedAmountOld = Math.round($('#sales_recived').val());
    function updatePay(){
        var totalAmount = Math.round($('#sales_grand_total').val());
        var receivedAmount = Math.round($('#sales_recived').val());
        var salesBalance = Math.round($('#sales_balance').val());
        receivedAmount += receivedAmountOld;
        $('#sales_recived').val(receivedAmount)
        var sales_balance = totalAmount - receivedAmount;
        $('#sales_balance').val(parseFloat(sales_balance).toFixed(2));
    }
    $(document).ready(function() {
        $("#sales_user_id").select2({
            placeholder: "Enter user",
            width:'100%',
            allowClear:true,
            maximumSelectionLength: 2
        });

        oTable = $('#emiTable').dataTable( {
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [
                    <?= $editAction;?>
            ],
            "sAjaxSource": "<?= $this->url('sales',array('action' => 'get-emi')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                aoData.push({ "name":"sales_id","value": $("#sales_id").val()} );
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        } );
    });

    function validateNow(){
        flag = deforayValidator.init({
            formId: 'payForm'
        });
        if(flag){
            conf=confirm("Are you sure, you want save this emi!");
            if(conf){
                $.blockUI();
                document.getElementById('payForm').submit();
            }
        }
    }
    $(document).ready(function() {
        <?php if(isset($result) && $result > 0) { ?>
            parent.closeModal();
        <?php } ?>
    });
</script>